
import React, { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  formatPrice: (price: number) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  zh: {
    'app.name': 'DESCU',
    'nav.search': '搜索宝贝、车辆、房产...',
    'nav.sell': '卖闲置',
    'nav.home': '首页',
    'nav.cart': '购物车',
    'nav.profile': '我的',
    'nav.login': '登录',
    'nav.chat': '消息',
    'hero.title': '身边好物，即刻成交',
    'hero.subtitle': 'DESCU 帮你发现5公里内的闲置宝藏。AI一键发布，交易就在转角。',
    'hero.cta': '立即探索',
    'list.header': '为您推荐',
    'list.search_results': '搜索结果',
    'list.items_count': '件商品',
    'list.loading_loc': '正在定位...',
    'list.loc_denied': '请开启定位',
    'list.loc_success': '附近',
    'list.empty': '暂无商品，快来发布第一个吧！',
    'list.no_results': '没有找到相关商品',
    'list.view_all': '查看所有商品',
    'card.nearby': '附近',
    'card.add_cart': '想要',
    'card.in_cart': '已添加',
    'card.promoted': '推广',
    'modal.title': '发布闲置',
    'modal.upload_text': '点击上传照片',
    'modal.upload_hint': 'AI将自动识别并填写信息',
    'modal.change_img': '更改图片',
    'modal.analyzing': 'AI 正在分析图片生成描述...',
    'modal.analyzed': 'AI 已为您自动填充信息',
    'modal.label.title': '标题',
    'modal.ph.title': '例如：95成新 iPhone 14',
    'modal.label.price': '价格',
    'modal.label.category': '分类',
    'modal.label.delivery': '交易方式',
    'modal.label.desc': '详细描述',
    'modal.ph.desc': '描述一下物品的新旧程度、入手渠道等...',
    'modal.loc.loading': '定位中...',
    'modal.loc.success': '位置已锁定',
    'modal.submit': '立即发布',
    'modal.submit.analyzing': '分析中...',
    'modal.policy_hint': '发布即表示您同意我们的内容政策，严禁发布仇恨言论或虚假政治信息。',
    'cart.title': '购物车',
    'cart.empty': '购物车空空如也',
    'cart.go_shop': '去逛逛',
    'cart.total': '合计',
    'cart.checkout': '立即结算',
    'cart.processing': '处理中...',
    'cart.success': '下单成功！',
    'cat.all': '全部',
    'cat.electronics': '数码',
    'cat.furniture': '家具',
    'cat.clothing': '服饰',
    'cat.books': '图书',
    'cat.sports': '运动',
    'cat.vehicles': '车辆',
    'cat.real_estate': '房产',
    'cat.services': '服务',
    'cat.other': '其他',
    'delivery.meetup': '当面交易',
    'delivery.shipping': '快递发货',
    'delivery.both': '面交/快递',
    'detail.back': '返回',
    'detail.seller': '卖家信息',
    'detail.verified': '已认证卖家',
    'detail.contact': '联系卖家',
    'detail.posted': '发布于',
    'detail.location': '交易地点',
    'detail.delivery': '配送方式',
    'detail.desc_title': '商品详情',
    'detail.recommend': '猜你喜欢',
    'detail.report': '举报此内容',
    'profile.title': '个人中心',
    'profile.avatar': '头像',
    'profile.change_avatar': '更换头像',
    'profile.name': '昵称',
    'profile.email': '邮箱',
    'profile.save': '保存修改',
    'profile.saved': '保存成功！',
    'profile.listings': '我发布的',
    'profile.no_listings': '暂无发布记录',
    'profile.verify_title': '身份认证',
    'profile.verify_desc': '提交身份证件，获得蓝盾标识，做值得信赖的卖家。',
    'profile.get_verified': '提交证件 (免费)',
    'profile.verifying': '审核中...',
    'profile.is_verified': '身份已认证',
    'profile.boost': '推广',
    'profile.safety_policies': '安全与政策',
    'profile.content_policy': '内容与政治规范',
    'profile.seo_manager': 'SEO 与管理中心',
    'profile.search_console': 'Google Search Console 状态',
    'profile.search_verified': '网站所有权已验证',
    'report.title': '举报内容',
    'report.reason': '举报原因',
    'report.reason.misinfo': '政治虚假信息',
    'report.reason.hate': '仇恨言论或歧视',
    'report.reason.scam': '诈骗或误导',
    'report.reason.prohibited': '禁止销售的物品',
    'report.reason.sensitive': '敏感政治宣传',
    'report.submit': '提交举报',
    'report.success': '感谢您的反馈，我们将进行审核。',
    'time.today': '今天',
    'time.days_ago': '{0}天前',
    'chat.inbox': '消息列表',
    'chat.type': '输入消息...',
    'chat.send': '发送',
    'chat.no_msgs': '暂无消息',
    'chat.empty_inbox': '还没有开始任何对话',
    'chat.you': '你',
  },
  en: {
    'app.name': 'DESCU',
    'nav.search': 'Search items, cars, homes...',
    'nav.sell': 'Sell',
    'nav.home': 'Home',
    'nav.cart': 'Cart',
    'nav.profile': 'Profile',
    'nav.login': 'Login',
    'nav.chat': 'Chat',
    'hero.title': 'Buy Local, Sell in a Flash',
    'hero.subtitle': 'Your AI-powered neighborhood marketplace. Find hidden gems within 5km.',
    'hero.cta': 'Explore Now',
    'list.header': 'Recommended for You',
    'list.search_results': 'Search Results',
    'list.items_count': 'items',
    'list.loading_loc': 'Locating...',
    'list.loc_denied': 'Enable Location',
    'list.loc_success': 'Nearby',
    'list.empty': 'No items yet. Be the first to sell!',
    'list.no_results': 'No items found',
    'list.view_all': 'View All',
    'card.nearby': 'Nearby',
    'card.add_cart': 'Add',
    'card.in_cart': 'Added',
    'card.promoted': 'Promoted',
    'modal.title': 'List Item',
    'modal.upload_text': 'Upload Photo',
    'modal.upload_hint': 'AI will auto-fill details',
    'modal.change_img': 'Change Photo',
    'modal.analyzing': 'AI analyzing...',
    'modal.analyzed': 'AI details generated',
    'modal.label.title': 'Title',
    'modal.ph.title': 'e.g., Like new iPhone 14',
    'modal.label.price': 'Price',
    'modal.label.category': 'Category',
    'modal.label.delivery': 'Delivery Method',
    'modal.label.desc': 'Description',
    'modal.ph.desc': 'Describe condition, usage, etc...',
    'modal.loc.loading': 'Locating...',
    'modal.loc.success': 'Location Locked',
    'modal.submit': 'Post Listing',
    'modal.submit.analyzing': 'Analyzing...',
    'modal.policy_hint': 'By posting, you agree to our policies. Hate speech and political misinformation are strictly prohibited.',
    'cart.title': 'Cart',
    'cart.empty': 'Your cart is empty',
    'cart.go_shop': 'Go Shopping',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.processing': 'Processing...',
    'cart.success': 'Order Placed!',
    'cat.all': 'All',
    'cat.electronics': 'Electronics',
    'cat.furniture': 'Furniture',
    'cat.clothing': 'Clothing',
    'cat.books': 'Books',
    'cat.sports': 'Sports',
    'cat.vehicles': 'Vehicles',
    'cat.real_estate': 'Real Estate',
    'cat.services': 'Services',
    'cat.other': 'Other',
    'delivery.meetup': 'Meetup Only',
    'delivery.shipping': 'Shipping Only',
    'delivery.both': 'Meetup & Shipping',
    'detail.back': 'Back',
    'detail.seller': 'Seller',
    'detail.verified': 'Verified Seller',
    'detail.contact': 'Chat with Seller',
    'detail.posted': 'Posted',
    'detail.location': 'Location',
    'detail.delivery': 'Delivery',
    'detail.desc_title': 'Description',
    'detail.recommend': 'Recommended',
    'detail.report': 'Report this listing',
    'profile.title': 'My Profile',
    'profile.avatar': 'Avatar',
    'profile.change_avatar': 'Change Photo',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.save': 'Save Changes',
    'profile.saved': 'Saved!',
    'profile.listings': 'My Listings',
    'profile.no_listings': 'No active listings',
    'profile.verify_title': 'Identity Verification',
    'profile.verify_desc': 'Upload your ID to become a trusted seller and boost sales.',
    'profile.get_verified': 'Submit ID (Free)',
    'profile.verifying': 'Uploading...',
    'profile.is_verified': 'Identity Verified',
    'profile.boost': 'Boost',
    'profile.safety_policies': 'Safety & Policies',
    'profile.content_policy': 'Content & Political Norms',
    'profile.seo_manager': 'SEO & Webmaster Center',
    'profile.search_console': 'Google Search Console Status',
    'profile.search_verified': 'Site Ownership Verified',
    'report.title': 'Report Content',
    'report.reason': 'Reason for reporting',
    'report.reason.misinfo': 'Political Misinformation',
    'report.reason.hate': 'Hate Speech or Discrimination',
    'report.reason.scam': 'Scam or Misleading',
    'report.reason.prohibited': 'Prohibited Item',
    'report.reason.sensitive': 'Sensitive Political Content',
    'report.submit': 'Submit Report',
    'report.success': 'Thank you for your report. We will review it shortly.',
    'time.today': 'Today',
    'time.days_ago': '{0} days ago',
    'chat.inbox': 'Messages',
    'chat.type': 'Type a message...',
    'chat.send': 'Send',
    'chat.no_msgs': 'No messages yet',
    'chat.empty_inbox': 'No conversations yet',
    'chat.you': 'You',
  },
  es: {
    'app.name': 'DESCU',
    'nav.search': 'Buscar autos, depas, servicios...',
    'nav.sell': 'Vender',
    'nav.home': 'Inicio',
    'nav.cart': 'Carrito',
    'nav.profile': 'Perfil',
    'nav.login': 'Entrar',
    'nav.chat': 'Mensajes',
    'hero.title': 'Compra en corto, vende de volada',
    'hero.subtitle': 'Tu tianguis digital con IA. Encuentra joyas ocultas a menos de 5km de ti.',
    'hero.cta': 'Ver Ofertas',
    'list.header': 'Recomendados',
    'list.search_results': 'Resultados',
    'list.items_count': 'artículos',
    'list.loading_loc': 'Ubicando...',
    'list.loc_denied': 'Activar Ubicación',
    'list.loc_success': 'Cerca de ti',
    'list.empty': '¡Sé el primero en vender algo!',
    'list.no_results': 'No se encontraron resultados',
    'list.view_all': 'Ver Todo',
    'card.nearby': 'Cerca',
    'card.add_cart': 'Lo quiero',
    'card.in_cart': 'Agregado',
    'card.promoted': 'Destacado',
    'modal.title': 'Publicar Anuncio',
    'modal.upload_text': 'Subir Foto',
    'modal.upload_hint': 'La IA llenará los datos por ti',
    'modal.change_img': 'Cambiar Foto',
    'modal.analyzing': 'IA analizando imagen...',
    'modal.analyzed': 'Datos generados por IA',
    'modal.label.title': 'Título',
    'modal.ph.title': 'ej. VW Jetta 2018 impecable',
    'modal.label.price': 'Precio',
    'modal.label.category': 'Categoría',
    'modal.label.delivery': 'Entrega',
    'modal.label.desc': 'Descripción',
    'modal.ph.desc': 'Detalles, condiciones, kilometraje...',
    'modal.loc.loading': 'Localizando...',
    'modal.loc.success': 'Ubicación agregada',
    'modal.submit': 'Publicar Ahora',
    'modal.submit.analyzing': 'Analizando...',
    'modal.policy_hint': 'Al publicar, aceptas nuestras políticas. Se prohíbe el discurso de odio y la desinformación política.',
    'cart.title': 'Carrito',
    'cart.empty': 'Tu carrito está vacío',
    'cart.go_shop': 'Ir a la tienda',
    'cart.total': 'Total',
    'cart.checkout': 'Comprar',
    'cart.processing': 'Procesando...',
    'cart.success': '¡Compra exitosa!',
    'cat.all': 'Todo',
    'cat.electronics': 'Electrónica',
    'cat.furniture': 'Hogar',
    'cat.clothing': 'Moda',
    'cat.books': 'Libros',
    'cat.sports': 'Deportes',
    'cat.vehicles': 'Autos',
    'cat.real_estate': 'Inmuebles',
    'cat.services': 'Servicios',
    'cat.other': 'Otros',
    'delivery.meetup': 'Entrega Personal',
    'delivery.shipping': 'Envío a Domicilio',
    'delivery.both': 'Entrega Personal o Envío',
    'detail.back': 'Volver',
    'detail.seller': 'Vendedor',
    'detail.verified': 'Vendedor Verificado',
    'detail.contact': 'Contactar Vendedor',
    'detail.posted': 'Publicado',
    'detail.location': 'Ubicación',
    'detail.delivery': 'Entrega',
    'detail.desc_title': 'Descripción',
    'detail.recommend': 'Te puede interesar',
    'detail.report': 'Reportar este anuncio',
    'profile.title': 'Mi Perfil',
    'profile.avatar': 'Foto de Perfil',
    'profile.change_avatar': 'Cambiar Foto',
    'profile.name': 'Nombre',
    'profile.email': 'Correo',
    'profile.save': 'Guardar Cambios',
    'profile.saved': '¡Guardado!',
    'profile.listings': 'Mis Publicaciones',
    'profile.no_listings': 'Sin publicaciones activas',
    'profile.verify_title': 'Verificación de Identidad',
    'profile.verify_desc': 'Sube tu identificación oficial (INE/Pasaporte) para ser un vendedor confiable.',
    'profile.get_verified': 'Subir ID (Gratis)',
    'profile.verifying': 'Subiendo...',
    'profile.is_verified': 'Identidad Verificada',
    'profile.boost': 'Destacar',
    'profile.safety_policies': 'Seguridad y Políticas',
    'profile.content_policy': 'Normas de Contenido y Política',
    'profile.seo_manager': 'SEO y Webmaster Center',
    'profile.search_console': 'Estado de Google Search Console',
    'profile.search_verified': 'Propiedad de Sitio Verificada',
    'report.title': 'Reportar Contenido',
    'report.reason': 'Motivo del reporte',
    'report.reason.misinfo': 'Desinformación Política',
    'report.reason.hate': 'Discurso de Odio o Discriminación',
    'report.reason.scam': 'Fraude o Engaño',
    'report.reason.prohibited': 'Artículo Prohibido',
    'report.reason.sensitive': 'Contenido Político Sensible',
    'report.submit': 'Enviar Reporte',
    'report.success': 'Gracias por tu reporte. Lo revisaremos a la brevedad.',
    'time.today': 'Hoy',
    'time.days_ago': 'Hace {0} días',
    'chat.inbox': 'Mensajes',
    'chat.type': 'Escribe un mensaje...',
    'chat.send': 'Enviar',
    'chat.no_msgs': 'Aún no hay mensajes',
    'chat.empty_inbox': 'No tienes conversaciones',
    'chat.you': 'Tú',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es'); 

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const formatPrice = (price: number) => {
    if (language === 'zh') {
      return `¥${price.toLocaleString()}`;
    } else {
      return `$${price.toLocaleString()}`;
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatPrice }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
